[options]
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
list_db = True
proxy_mode = False

# Mode development: workers=0 (1 worker). Untuk produksi sesuaikan.
workers = 0
max_cron_threads = 1